### ISSUE TITLE
Something's not right. Make sure the Leap Motion is connected

### ISSUE THREAD

**Issue by luis84** [hsocasnavarro/DesktopLeapr#1]
Hello,

Love the idea.  I am running Leap on LM 14.  I started up leapd and it is proper.  I can verify it works by running Visualizer& and I can see it works.

When I run python desktopleapr.py it returns this output though:

Xlib.protocol.request.QueryExtension
Screen size is: 4800 900
Initializing Leap Motion...
Something's not right. Make sure the Leap Motion is connected
and the leapd daemon is running

**Comment by hsocasnavarro** [comment]
That message shows it's not been able to collect 20 good frames during the initialization. It usually happens when leapd is not running or the LM is not connected. However, you say that you can run visualizer so that's clearly not the problem. Perhaps the LM has gone into standby mode? Try waving your hand over the device for a few seconds and start the Leapr again. Or start the Leapr immediately after running visualizer. If this doesn't work please let me know and we'll try some debugging. Thanks!

Hector

**Comment by titcombj** [comment]
I'm having the same issue, the leap is connected and running with visualiser, the IR led's re visible when I run "python desktopleapr.py &" I get the same result. 

I first noticed this issue after installing Compiz, I had the system working prior to this, but wanted to try out rotating the desk top cube. I'm not at all sure it is related, but it wouldn't work after installing Compiz. 

My system is Linux Mint 14 with a Mate desktop. 

I notice that if I change nframes=1 then it seems to work:-

python desktopleapr.py
Xlib.protocol.request.QueryExtension
Screen size is: 1600 1200
Initializing Leap Motion...
Frame buffer sizes: 1 1
Initialized
Connected
Press Enter to quit...
scrolling down  4
scrolling up  5
scrolling down  2
scrolling down  5
scrolling up  5
scrolling down  5
scrolling up  5
scrolling down  5

**Comment by titcombj** [comment]
Hector,
I've tried different settings for nframes, I can put it up to 7 and still initialize the Leap Motion, if I go higher than that then it fails. Alternately I can increase the itry limit :- "if itry == 2e5" and have it initialize with nframes=10 

With itry == 1e5 it's taking my machine between 450 and 600ms to get round the loop and time out. Visualiser seems nice and smooth, but it is reporting a frame rate of between 24 and 30 fps so this would fit in with my findings.

**Comment by hsocasnavarro** [comment]
Folks, this is very interesting information, thank you. Working on a fix and will hopefully upload a new version in the next hours.
titcombj: it could be that different architectures require a different number of iterations to collect the right number of frames. I'm going to replace that counter with a timeout. PS: I use Compiz as well

**Comment by hsocasnavarro** [comment]
Ok, the new version has been uploaded. Could you please check and see if it works now?

Thanks

**Comment by titcombj** [comment]
Hector,
Works for me just fine
Thanks
Jim.

**Comment by hsocasnavarro** [comment]
Great. I'll close this issue then. Feel free to open a new one if you see another problem
